# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "af4a90c3a1d4f537cf7149813207fec9"
name = "restrocheckoutui"
application_url = "https://supplied-neighbor-whats-future.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "retrospecdevelopmentstore.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_companies,read_customers,read_draft_orders,write_customers,write_draft_orders"

[auth]
redirect_urls = [
  "https://supplied-neighbor-whats-future.trycloudflare.com/auth/callback",
  "https://supplied-neighbor-whats-future.trycloudflare.com/auth/shopify/callback",
  "https://supplied-neighbor-whats-future.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
